version: "3"
services:
    frontend:
        tty: true
        stdin_open: false
        container_name: react
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "3000:3000"